services:
  mongo:
    image: mongo:7
    container_name: lab7_mongo_db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: library
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: lab7_redis
    restart: always
    ports:
      - "6380:6379"

  api:
    build: .
    container_name: lab7_fastapi_app
    depends_on:
      - mongo
      - redis
    ports:
      - "8004:8000"
    environment:
      MONGO_URL: mongodb://mongo:27017
      MONGO_DB: library
      REDIS_URL: redis://redis:6379/0
      SECRET_KEY: lab7-demo-secret
      AUTH_USERNAME: admin
      AUTH_PASSWORD: secret
    command: >
      sh -c "sleep 5 && uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  mongo_data:
